name: Build Masscan Binary

# Déclencheurs du workflow
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  release:
    types: [ "created" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make gcc libpcap-dev
      
      - name: Build Masscan
        run: make -j$(nproc)
      
      # Sauvegarde le binaire en tant qu'artifact
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: masscan-linux-x86_64
          path: bin/masscan
          retention-days: 30
      
      # Si c'est une release, attache le binaire à la release
      - name: Upload binary to release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/masscan
          asset_name: masscan-linux-x86_64
          tag: ${{ github.ref }}
          overwrite: true
